In [1]:
import numpy as np
import math
import random

In [31]:
class main :

#Pembentukan Chromosome
	populasi = 6 
	gen = ["a", "b", "c", "d"] 
	batas_nilai = {
		'min' : 0,
		'max' : 10
	} 
	crossover = 50/100 
	mutasi_rate = 10/100 
	total_gen = 24
  
	next_gen = np.arange(4)
	stop = False

#Inisialisasi    
	def __init__(self):
		self.first_chrom = np.random.randint(low=self.batas_nilai['min'], high=self.batas_nilai['max'], size=(self.populasi, len(self.gen)))
		print("Inisialisasi")
		print(self.first_chrom)
		print(" ")

#Evaluasi Chromosome
	def evaluasi_chrom(self, chrom, generasi):
   
		# Mencari Fungsi Objektif
		
		print("Generasi ke-"+str(generasi+1)+"")
		
		jumlah_chromo = len(chrom)
		o = np.arange(jumlah_chromo)   
		fitness = np.arange(jumlah_chromo, dtype='f')
		
		for x in range(len(chrom)):
		
			#Fungsi Objektif 
			fo = abs((chrom[x][0]+2*chrom[x][1]+3*chrom[x][2]+4*chrom[x][3])-30)
			o[x] = fo
			
			#Seleksi Chromosome dan Mencari Fitness
			fitn = 1/(fo+1)
			
			fitness[x] = fitn
			if(fitn == 1):
				self.stop = True
			print("Chromosome {0} : {1}, fitness = {2}".format(x+1, np.array2string(chrom[x], separator=','), fitn))
		print(o)
		
        
#Probabilitas
		Probab = np.arange(jumlah_chromo, dtype='f')
  
		total_fitness = fitness.sum() 
		Probab = fitness / total_fitness 
		print("Total fitness : {}".format(str(total_fitness)))
		print("Rata-rata fitness : {}".format(str(np.average(fitness))))
		print("Probabilitas : {}".format(np.array2string(Probab, separator=',')))
		print("Probabilitas Paling Tinggi : {}, Pada chromosome ke {}".format(Probab[Probab.argmax()], str(Probab.argmax()+1)))
		print("Chromosome yang mungkin terpilih pada generasi selanjutnya : {}".format(np.array2string(chrom[Probab.argmax()], separator=',')))
		print("")
		print("")
		self.next_gen = chrom[Probab.argmax()]

#mencari nilai kumulatif
		C = np.arange(jumlah_chromo, dtype='f')
		total_x = 0
		for x in range(len(Probab)):
			total_x += Probab[x]
			C[x] = total_x

#roulette wheel sebanyak jumlah populasi
		R = np.random.sample(len(fitness))
		chrom_baru = np.arange(jumlah_chromo*len(self.gen)).reshape(jumlah_chromo, len(self.gen))


#mencari chromosome baru dari roulette wheel
		for y in range(len(R)):
			for k in range(len(chrom_baru)):
				if(R[y] < C[0]):
					chrom_baru[y] = chrom[0]
				elif((C[k-1] < R[y]) & (R[y] < C[k])):
					chrom_baru[y] = chrom[k]

#mencari crossover chromosome
		R = np.random.sample(jumlah_chromo)
		index_chrome_induk = [] # [1,2,3, ...]
		for p in range(len(R)):
			if(R[p] < self.crossover):
				index_chrome_induk.append(p)
                
#menentukan posisi crossover
		posisi_cros = np.random.randint(low=1, high=len(self.gen), size=len(index_chrome_induk))

#menentukan posisi cut-point crossover
		offspring = np.arange(len(self.gen)*len(index_chrome_induk)).reshape(len(index_chrome_induk), len(self.gen))
		for i_parent in range(len(index_chrome_induk)):
			index_chrome_1 = index_chrome_induk[i_parent]
			if(i_parent == len(index_chrome_induk)-1):
				index_chrome_2 = index_chrome_induk[0]
			else:
				index_chrome_2 = index_chrome_induk[i_parent+1]
			#melakukan cut-point
			cut_point = posisi_cros[i_parent]
			for p in range(len(chrom_baru[index_chrome_1])):
				if(p >= posisi_cros[i_parent]):
					offspring[i_parent][p] = chrom_baru[index_chrome_2][p]
				else:
					offspring[i_parent][p] = chrom_baru[index_chrome_1][p]

		for x in range(len(offspring)):
			chrom_baru[index_chrome_induk[x]] = offspring[x]
            
#mutasi chromosome
		total_gen = len(chrom) * len(chrom[0])
		jum_mutasi = self.mutasi_rate * total_gen #rumus menghitung jumlah mutasi
		jum_mutasi = int(jum_mutasi)

		random_i_mutasi = np.random.randint(low=0, high=total_gen, size=jum_mutasi)

		for x in range(len(random_i_mutasi)):
			index_mutasi = random_i_mutasi[x]
			byk_kromosom = len(chrom)
			byk_gen = len(chrom[0])
			random_value = random.randint(self.batas_nilai['min'], self.batas_nilai['max'])
			if(index_mutasi <= byk_gen):
				#jika index_mutasi <= banyak gen, maka akan mengganti
				#gen pada chromosome baru yang ke-1
				chrom_baru[0][index_mutasi-1]
			else:
				#POSISI Y DARI KROMOSOM, UNTUK MENCARI INDEX
				posisi_y = index_mutasi/byk_gen
				posisi_y = int(posisi_y)
				posisi_x = index_mutasi % byk_gen
				chrom_baru[posisi_y][posisi_x] = random_value
		return chrom_baru

	def do_now(self):
		chromosome_current = self.first_chrom
		for generasi in range(0, self.total_gen):
			if(self.stop != True):
				chromosome_current = self.evaluasi_chrom(chromosome_current, generasi)
		print("----------------------------------------------------------------------")
		print("Chromosome yang terpilih adalah")
		print(self.next_gen)

run = algo_genetika()
run.do_now()

Inisialisasi
[[2 4 9 7]
 [4 9 9 8]
 [9 2 7 6]
 [8 3 8 1]
 [5 6 8 5]
 [7 4 2 6]]
 
Generasi ke-1
Chromosome 1 : [2,4,9,7], fitness = 0.027777777777777776
Chromosome 2 : [4,9,9,8], fitness = 0.019230769230769232
Chromosome 3 : [9,2,7,6], fitness = 0.034482758620689655
Chromosome 4 : [8,3,8,1], fitness = 0.07692307692307693
Chromosome 5 : [5,6,8,5], fitness = 0.03125
Chromosome 6 : [7,4,2,6], fitness = 0.0625
[35 51 28 12 31 15]
Total fitness : 0.2521644
Rata-rata fitness : 0.0420274
Probabilitas : [0.11015742,0.07626283,0.13674714,0.30505133,0.12392709,0.24785419]
Probabilitas Paling Tinggi : 0.305051326751709, Pada chromosome ke 4
Chromosome yang mungkin terpilih pada generasi selanjutnya : [8,3,8,1]


Generasi ke-2
Chromosome 1 : [8,3,8,1], fitness = 0.07692307692307693
Chromosome 2 : [8,4,9,7], fitness = 0.023809523809523808
Chromosome 3 : [9,2,7,6], fitness = 0.034482758620689655
Chromosome 4 : [2,4,2,6], fitness = 0.09090909090909091
Chromosome 5 : [4,9,9,8], fitness = 0.01923076923